services:
  simplistics:
    image: simplistics
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5055:5055'
    environment:
      - NODE_ENV=production
      - PORT=5055
      - DB=store.db
