services:
  simplistics:
    image: monollect/simplistics:latest
    ports:
      - '5055:5055'
    environment:
      - NODE_ENV=production
      - PORT=5055
      - DB=store.db
      - ALLOWED_HOSTS=http://localhost:3000,https://syntaxpunk.com
