# fly.toml app configuration file generated for simplistics on 2024-05-29T12:29:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simplistics'
primary_region = 'arn'

[build]
  image = 'monollect/simplistics:latest'

[http_service]
  internal_port = 5055
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "db_volume"
  destination = "/data"
