# fly.toml app configuration file generated for simplistics on 2024-05-30T16:18:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simplistics'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 5055
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
